# Generated by Django 4.2 on 2024-10-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='id_autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
