# Generated by Django 4.2 on 2024-10-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_id_autor_libro_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito')], default='debito', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito')], max_length=7),
        ),
    ]
