# Generated by Django 4.2 on 2024-11-02 16:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_metodopago_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
